name: release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run tests
        run: go test
      - name: Build binaries
        run: |
          GOOS=windows GOARCH=amd64 go build -o build/scago-${{ github.ref_name }}-windows-x86_64.exe
          GOOS=windows GOARCH=arm64 go build -o build/scago-${{ github.ref_name }}-windows-arm64.exe
          GOOS=windows GOARCH=386 go build -o build/scago-${{ github.ref_name }}-windows-i386.exe
          GOOS=darwin GOARCH=amd64 go build -o build/scago-${{ github.ref_name }}-darwin-x86_64
          GOOS=darwin GOARCH=arm64 go build -o build/scago-${{ github.ref_name }}-darwin-arm64
          GOOS=linux GOARCH=amd64 go build -o build/scago-${{ github.ref_name }}-linux-x86_64
          GOOS=linux GOARCH=arm64 go build -o build/scago-${{ github.ref_name }}-linux-aarch64
          GOOS=linux GOARCH=386 go build -o build/scago-${{ github.ref_name }}-linux-i386
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*